root - INFO - 2023-02-20 09:32:45.103671 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - CRITICAL - CRITICAL ERROR:2023-02-20 09:32:45.133235 - Failed to initialise Log server/ADS.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/Backend/Scripts/Main.py", line 35, in __init__', "    self.log_interface.postLog(severity='INFO',message='Finvant Alcubierre Mk1 OMS Backend turned on.', publish=1)", '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/Backend/Scripts/Log_Server_Interface.py", line 55, in postLog', "    response = requests.post(self.url + 'post/log', headers=headers, json=json_compatible_item_data)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 117, in post', "    return request('post', url, data=data, json=json, **kwargs)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 61, in request', '    return session.request(method=method, url=url, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 529, in request', '    resp = self.send(prep, **send_kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 645, in send', '    r = adapter.send(request, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 440, in send', '    resp = conn.urlopen(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen', '    httplib_response = self._make_request(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request', '    six.raise_from(e, None)', '  File "<string>", line 3, in raise_from', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request', '    httplib_response = conn.getresponse()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1377, in getresponse', '    response.begin()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 320, in begin', '    version, status, reason = self._read_status()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 281, in _read_status', '    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto', '    return self._sock.recv_into(b)', 'KeyboardInterrupt']
root - INFO - 2023-02-20 09:32:52.891619 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-02-20 09:32:52.997036 - OMS Backend mainloop started.
root - INFO - 2023-02-20 09:32:55.107709 - OMSB: Logging in for backend kite ticker.
root - CRITICAL - CRITICAL ERROR:2023-02-20 09:33:02.835174 - OMSB: Failed auto login to kite ticker.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/Backend/Scripts/AutoLoginKiteTicker.py", line 54, in automate_login', '    time.sleep(1)', 'KeyboardInterrupt', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/Backend/Scripts/AutoLoginKiteTicker.py", line 124, in auto_login_zerodha_ticker', '    key = automate_login(browser_url, user_id, password, totp_pin, debug=debug)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/Backend/Scripts/AutoLoginKiteTicker.py", line 61, in automate_login', '    time.sleep(1)', 'KeyboardInterrupt']
root - CRITICAL - CRITICAL ERROR:2023-02-20 09:33:02.952699 - Failed to initialise LTP gather module.
['Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn', '    conn = connection.create_connection(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection', '    raise err', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection', '    sock.connect(sa)', 'ConnectionRefusedError: [Errno 61] Connection refused', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen', '    httplib_response = self._make_request(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request', '    conn.request(method, url, **httplib_request_kw)', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request', '    super(HTTPConnection, self).request(method, url, body=body, headers=headers)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request', '    self._send_request(method, url, body, headers, encode_chunked)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1331, in _send_request', '    self.endheaders(body, encode_chunked=encode_chunked)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1280, in endheaders', '    self._send_output(message_body, encode_chunked=encode_chunked)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1040, in _send_output', '    self.send(msg)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 980, in send', '    self.connect()', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect', '    conn = self._new_conn()', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn', '    raise NewConnectionError(', 'urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1236bc2b0>: Failed to establish a new connection: [Errno 61] Connection refused', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 440, in send', '    resp = conn.urlopen(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen', '    retries = retries.increment(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment', '    raise MaxRetryError(_pool, url, error or ResponseError(cause))', "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1236bc2b0>: Failed to establish a new connection: [Errno 61] Connection refused'))", '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/Backend/Scripts/GatherLTP.py", line 30, in __init__', '    self.OMS_interface = OMS_API_Interface.OMS_Interface(Config().OMS_SERVER_ADDRESS)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/Backend/Scripts/OMS_API_Interface.py", line 12, in __init__', '    self.token = self.authentification()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/Backend/Scripts/OMS_API_Interface.py", line 23, in authentification', "    response = requests.post(self.url + 'token', data=data)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 117, in post', "    return request('post', url, data=data, json=json, **kwargs)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 61, in request', '    return session.request(method=method, url=url, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 529, in request', '    resp = self.send(prep, **send_kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 645, in send', '    r = adapter.send(request, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 519, in send', '    raise ConnectionError(e, request=request)', "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1236bc2b0>: Failed to establish a new connection: [Errno 61] Connection refused'))"]
root - CRITICAL - CRITICAL ERROR:2023-02-20 09:33:03.011699 - Failed to start LTP thread.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/Backend/Scripts/Main.py", line 65, in main_loop', '    g = GatherLTP(kws = kite_ticker, log_interface = self.log_interface)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/Backend/Scripts/GatherLTP.py", line 47, in __init__', '    self.log_interface.postLog(severity="CRITICAL",message=\'Failed to initialise LTP gather module.\',publish = 1, tag = \'OMSB_GLTP_1\')', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/Backend/Scripts/Log_Server_Interface.py", line 55, in postLog', "    response = requests.post(self.url + 'post/log', headers=headers, json=json_compatible_item_data)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 117, in post', "    return request('post', url, data=data, json=json, **kwargs)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 61, in request', '    return session.request(method=method, url=url, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 529, in request', '    resp = self.send(prep, **send_kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 645, in send', '    r = adapter.send(request, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 440, in send', '    resp = conn.urlopen(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen', '    httplib_response = self._make_request(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request', '    six.raise_from(e, None)', '  File "<string>", line 3, in raise_from', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request', '    httplib_response = conn.getresponse()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1377, in getresponse', '    response.begin()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 320, in begin', '    version, status, reason = self._read_status()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 281, in _read_status', '    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto', '    return self._sock.recv_into(b)', 'KeyboardInterrupt']
root - INFO - 2023-02-20 09:33:03.128168 - OMSB: Zerodha login for WG5235.
root - CRITICAL - CRITICAL ERROR:2023-02-20 09:33:03.176753 - Failed to generate user dictionary.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/Backend/Scripts/Main.py", line 72, in main_loop', '    user_dict = UserProfileGenerator().create_user_profiles(user_data=user_data, log_interface=self.log_interface, debug=self.DEBUG)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/Backend/Scripts/UserProfileGenerator.py", line 68, in create_user_profiles', '    t.join()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1053, in join', '    self._wait_for_tstate_lock()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1073, in _wait_for_tstate_lock', '    if lock.acquire(block, timeout):', 'KeyboardInterrupt']
root - CRITICAL - CRITICAL ERROR:2023-02-20 09:33:03.303685 - Failure in order handler.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/Backend/Scripts/Main.py", line 78, in main_loop', '    order_handler = OrderHandler(user_profiles=user_dict, spread_list=spread_list, log_interface = self.log_interface, debug=self.DEBUG)', "UnboundLocalError: local variable 'user_dict' referenced before assignment"]
root - CRITICAL - CRITICAL ERROR:2023-02-20 09:33:03.342595 - Failed to initialise Log server/ADS.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/Backend/Scripts/Main.py", line 36, in __init__', '    self.start()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/Backend/Scripts/Main.py", line 44, in start', '    self.main_loop()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/Backend/Scripts/Main.py", line 81, in main_loop', '    self.log_interface.postLog(severity="CRITICAL",message=\'Failure in order handler.\',publish = 1, tag = \'OMSB_MAIN_5\')', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/Backend/Scripts/Log_Server_Interface.py", line 55, in postLog', "    response = requests.post(self.url + 'post/log', headers=headers, json=json_compatible_item_data)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 117, in post', "    return request('post', url, data=data, json=json, **kwargs)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 61, in request', '    return session.request(method=method, url=url, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 529, in request', '    resp = self.send(prep, **send_kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 645, in send', '    r = adapter.send(request, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 440, in send', '    resp = conn.urlopen(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen', '    httplib_response = self._make_request(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request', '    six.raise_from(e, None)', '  File "<string>", line 3, in raise_from', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request', '    httplib_response = conn.getresponse()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1377, in getresponse', '    response.begin()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 320, in begin', '    version, status, reason = self._read_status()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 281, in _read_status', '    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto', '    return self._sock.recv_into(b)', 'KeyboardInterrupt']
root - INFO - 2023-02-20 09:45:53.997977 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-02-20 09:45:54.106032 - OMS Backend mainloop started.
root - INFO - 2023-02-20 09:45:56.184948 - OMSB: Logging in for backend kite ticker.
root - INFO - 2023-02-20 09:46:06.245271 - OMSB: Login succesful for backend kite ticker.
root - CRITICAL - CRITICAL ERROR:2023-02-20 09:46:06.417660 - Failed to initialise LTP gather module.
['Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn', '    conn = connection.create_connection(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection', '    raise err', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection', '    sock.connect(sa)', 'ConnectionRefusedError: [Errno 61] Connection refused', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen', '    httplib_response = self._make_request(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request', '    conn.request(method, url, **httplib_request_kw)', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request', '    super(HTTPConnection, self).request(method, url, body=body, headers=headers)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request', '    self._send_request(method, url, body, headers, encode_chunked)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1331, in _send_request', '    self.endheaders(body, encode_chunked=encode_chunked)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1280, in endheaders', '    self._send_output(message_body, encode_chunked=encode_chunked)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1040, in _send_output', '    self.send(msg)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 980, in send', '    self.connect()', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect', '    conn = self._new_conn()', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn', '    raise NewConnectionError(', 'urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x161c53280>: Failed to establish a new connection: [Errno 61] Connection refused', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 440, in send', '    resp = conn.urlopen(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen', '    retries = retries.increment(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment', '    raise MaxRetryError(_pool, url, error or ResponseError(cause))', "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x161c53280>: Failed to establish a new connection: [Errno 61] Connection refused'))", '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/GatherLTP.py", line 30, in __init__', '    self.OMS_interface = OMS_API_Interface.OMS_Interface(Config().OMS_SERVER_ADDRESS)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/OMS_API_Interface.py", line 12, in __init__', '    self.token = self.authentification()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/OMS_API_Interface.py", line 23, in authentification', "    response = requests.post(self.url + 'token', data=data)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 117, in post', "    return request('post', url, data=data, json=json, **kwargs)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 61, in request', '    return session.request(method=method, url=url, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 529, in request', '    resp = self.send(prep, **send_kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 645, in send', '    r = adapter.send(request, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 519, in send', '    raise ConnectionError(e, request=request)', "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x161c53280>: Failed to establish a new connection: [Errno 61] Connection refused'))"]
root - INFO - 2023-02-20 09:46:06.526101 - Attempting XTS login.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
root - INFO - 2023-02-20 09:46:06.699083 - OMSB: Zerodha login for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
root - CRITICAL - CRITICAL ERROR:2023-02-20 09:46:09.763349 - Failed to generate user dictionary.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 72, in main_loop', '    user_dict = UserProfileGenerator().create_user_profiles(user_data=user_data, log_interface=self.log_interface, debug=self.DEBUG)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/UserProfileGenerator.py", line 68, in create_user_profiles', '    t.join()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1053, in join', '    self._wait_for_tstate_lock()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1073, in _wait_for_tstate_lock', '    if lock.acquire(block, timeout):', 'KeyboardInterrupt']
root - CRITICAL - CRITICAL ERROR:2023-02-20 09:46:09.782056 - OMSB: Failed auto login to kite for user:WG5235.
['Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen', '    httplib_response = self._make_request(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request', '    six.raise_from(e, None)', '  File "<string>", line 3, in raise_from', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request', '    httplib_response = conn.getresponse()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1377, in getresponse', '    response.begin()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 320, in begin', '    version, status, reason = self._read_status()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 289, in _read_status', '    raise RemoteDisconnected("Remote end closed connection without"', 'http.client.RemoteDisconnected: Remote end closed connection without response', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/AutoLoginZerodha.py", line 37, in automate_login', '    browser.get(browser_url)', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 437, in get', "    self.execute(Command.GET, {'url': url})", '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 423, in execute', '    response = self.command_executor.execute(driver_command, params)', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 333, in execute', '    return self._request(command_info[0], url, body=data)', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 355, in _request', '    resp = self._conn.request(method, url, body=body, headers=headers)', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/request.py", line 78, in request', '    return self.request_encode_body(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/request.py", line 170, in request_encode_body', '    return self.urlopen(method, url, **extra_kw)', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/poolmanager.py", line 376, in urlopen', '    response = conn.urlopen(method, u.request_uri, **kw)', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen', '    retries = retries.increment(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment', '    raise six.reraise(type(error), error, _stacktrace)', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise', '    raise value.with_traceback(tb)', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen', '    httplib_response = self._make_request(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request', '    six.raise_from(e, None)', '  File "<string>", line 3, in raise_from', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request', '    httplib_response = conn.getresponse()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1377, in getresponse', '    response.begin()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 320, in begin', '    version, status, reason = self._read_status()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 289, in _read_status', '    raise RemoteDisconnected("Remote end closed connection without"', "urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))", '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 71, in start', '    self.process = subprocess.Popen(cmd, env=self.env,', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__', '    self._execute_child(args, executable, preexec_fn, close_fds,', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child', '    raise child_exception_type(errno_num, err_msg, err_filename)', "FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'", '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/AutoLoginZerodha.py", line 117, in auto_login_zerodha', '    key = automate_login(browser_url, user_id, password, totp_pin)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/AutoLoginZerodha.py", line 40, in automate_login', '    browser = webdriver.Chrome(options = options)', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__', '    super(WebDriver, self).__init__(DesiredCapabilities.CHROME[\'browserName\'], "goog",', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__', '    self.service.start()', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 81, in start', '    raise WebDriverException(', "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home", '']
root - CRITICAL - CRITICAL ERROR:2023-02-20 09:46:09.888120 - Failure in order handler.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 78, in main_loop', '    order_handler = OrderHandler(user_profiles=user_dict, spread_list=spread_list, log_interface = self.log_interface, debug=self.DEBUG)', "UnboundLocalError: local variable 'user_dict' referenced before assignment"]
root - CRITICAL - CRITICAL ERROR:2023-02-20 09:46:09.974267 - Failed to initialise Log server/ADS.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 36, in __init__', '    self.start()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 44, in start', '    self.main_loop()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 81, in main_loop', '    self.log_interface.postLog(severity="CRITICAL",message=\'Failure in order handler.\',publish = 1, tag = \'OMSB_MAIN_5\')', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Log_Server_Interface.py", line 55, in postLog', "    response = requests.post(self.url + 'post/log', headers=headers, json=json_compatible_item_data)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 117, in post', "    return request('post', url, data=data, json=json, **kwargs)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 61, in request', '    return session.request(method=method, url=url, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 529, in request', '    resp = self.send(prep, **send_kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 645, in send', '    r = adapter.send(request, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 440, in send', '    resp = conn.urlopen(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen', '    httplib_response = self._make_request(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request', '    six.raise_from(e, None)', '  File "<string>", line 3, in raise_from', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request', '    httplib_response = conn.getresponse()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1377, in getresponse', '    response.begin()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 320, in begin', '    version, status, reason = self._read_status()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 281, in _read_status', '    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto', '    return self._sock.recv_into(b)', 'KeyboardInterrupt']
root - INFO - 2023-02-20 09:47:25.513612 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-02-20 09:47:25.627935 - OMS Backend mainloop started.
root - INFO - 2023-02-20 09:47:27.640976 - OMSB: Logging in for backend kite ticker.
root - CRITICAL - CRITICAL ERROR:2023-02-20 09:47:31.002859 - OMSB: Failed auto login to kite ticker.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/AutoLoginKiteTicker.py", line 36, in automate_login', "    browser = webdriver.Chrome(options = options,executable_path='../Chrome/chromedriver')", '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__', '    super(WebDriver, self).__init__(DesiredCapabilities.CHROME[\'browserName\'], "goog",', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__', '    RemoteWebDriver.__init__(', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 269, in __init__', '    self.start_session(capabilities, browser_profile)', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in start_session', '    response = self.execute(Command.NEW_SESSION, parameters)', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute', '    self.error_handler.check_response(response)', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response', '    raise exception_class(message, screen, stacktrace)', 'selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 107', 'Current browser version is 109.0.5414.119 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome', 'Stacktrace:', '0   chromedriver                        0x00000001012482c8 chromedriver + 4752072', '1   chromedriver                        0x00000001011c8463 chromedriver + 4228195', '2   chromedriver                        0x0000000100e2bb18 chromedriver + 441112', '3   chromedriver                        0x0000000100e57f9b chromedriver + 622491', '4   chromedriver                        0x0000000100e53046 chromedriver + 602182', '5   chromedriver                        0x0000000100e4ee3c chromedriver + 585276', '6   chromedriver                        0x0000000100e91c43 chromedriver + 859203', '7   chromedriver                        0x0000000100e9174f chromedriver + 857935', '8   chromedriver                        0x0000000100e89b33 chromedriver + 826163', '9   chromedriver                        0x0000000100e5a9fd chromedriver + 633341', '10  chromedriver                        0x0000000100e5c051 chromedriver + 639057', '11  chromedriver                        0x000000010121530e chromedriver + 4543246', '12  chromedriver                        0x0000000101219a88 chromedriver + 4561544', '13  chromedriver                        0x00000001012216df chromedriver + 4593375', '14  chromedriver                        0x000000010121a8fa chromedriver + 4565242', '15  chromedriver                        0x00000001011f02cf chromedriver + 4391631', '16  chromedriver                        0x00000001012395b8 chromedriver + 4691384', '17  chromedriver                        0x0000000101239739 chromedriver + 4691769', '18  chromedriver                        0x000000010124f81e chromedriver + 4782110', '19  libsystem_pthread.dylib             0x00007ff81f61d4e1 _pthread_start + 125', '20  libsystem_pthread.dylib             0x00007ff81f618f6b thread_start + 15', '', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 71, in start', '    self.process = subprocess.Popen(cmd, env=self.env,', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__', '    self._execute_child(args, executable, preexec_fn, close_fds,', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child', '    raise child_exception_type(errno_num, err_msg, err_filename)', "FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'", '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/AutoLoginKiteTicker.py", line 124, in auto_login_zerodha_ticker', '    key = automate_login(browser_url, user_id, password, totp_pin, debug=debug)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/AutoLoginKiteTicker.py", line 40, in automate_login', '    browser = webdriver.Chrome(options = options)', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__', '    super(WebDriver, self).__init__(DesiredCapabilities.CHROME[\'browserName\'], "goog",', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__', '    self.service.start()', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 81, in start', '    raise WebDriverException(', "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home", '']
root - CRITICAL - CRITICAL ERROR:2023-02-20 09:47:31.112699 - Failed to initialise LTP gather module.
['Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn', '    conn = connection.create_connection(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection', '    raise err', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection', '    sock.connect(sa)', 'ConnectionRefusedError: [Errno 61] Connection refused', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen', '    httplib_response = self._make_request(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request', '    conn.request(method, url, **httplib_request_kw)', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request', '    super(HTTPConnection, self).request(method, url, body=body, headers=headers)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request', '    self._send_request(method, url, body, headers, encode_chunked)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1331, in _send_request', '    self.endheaders(body, encode_chunked=encode_chunked)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1280, in endheaders', '    self._send_output(message_body, encode_chunked=encode_chunked)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1040, in _send_output', '    self.send(msg)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 980, in send', '    self.connect()', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect', '    conn = self._new_conn()', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn', '    raise NewConnectionError(', 'urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11cc7e760>: Failed to establish a new connection: [Errno 61] Connection refused', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 440, in send', '    resp = conn.urlopen(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen', '    retries = retries.increment(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment', '    raise MaxRetryError(_pool, url, error or ResponseError(cause))', "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11cc7e760>: Failed to establish a new connection: [Errno 61] Connection refused'))", '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/GatherLTP.py", line 30, in __init__', '    self.OMS_interface = OMS_API_Interface.OMS_Interface(Config().OMS_SERVER_ADDRESS)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/OMS_API_Interface.py", line 12, in __init__', '    self.token = self.authentification()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/OMS_API_Interface.py", line 23, in authentification', "    response = requests.post(self.url + 'token', data=data)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 117, in post', "    return request('post', url, data=data, json=json, **kwargs)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 61, in request', '    return session.request(method=method, url=url, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 529, in request', '    resp = self.send(prep, **send_kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 645, in send', '    r = adapter.send(request, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 519, in send', '    raise ConnectionError(e, request=request)', "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11cc7e760>: Failed to establish a new connection: [Errno 61] Connection refused'))"]
root - CRITICAL - CRITICAL ERROR:2023-02-20 09:47:31.218216 - Failed to start KWS thread.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/GatherLTP.py", line 71, in start', '    self.kws.on_ticks = self.on_ticks', "AttributeError: 'NoneType' object has no attribute 'on_ticks'"]
root - INFO - 2023-02-20 09:47:31.218568 - Attempting XTS login.
root - INFO - 2023-02-20 09:47:31.446015 - OMSB: Zerodha login for WG5235.
root - CRITICAL - CRITICAL ERROR:2023-02-20 09:47:32.427586 - OMSB: Failed auto login to kite for user:WG5235.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/AutoLoginZerodha.py", line 36, in automate_login', "    browser = webdriver.Chrome(options = options,executable_path='../Chrome/chromedriver')", '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__', '    super(WebDriver, self).__init__(DesiredCapabilities.CHROME[\'browserName\'], "goog",', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__', '    RemoteWebDriver.__init__(', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 269, in __init__', '    self.start_session(capabilities, browser_profile)', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in start_session', '    response = self.execute(Command.NEW_SESSION, parameters)', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute', '    self.error_handler.check_response(response)', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response', '    raise exception_class(message, screen, stacktrace)', 'selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 107', 'Current browser version is 109.0.5414.119 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome', 'Stacktrace:', '0   chromedriver                        0x00000001009cc2c8 chromedriver + 4752072', '1   chromedriver                        0x000000010094c463 chromedriver + 4228195', '2   chromedriver                        0x00000001005afb18 chromedriver + 441112', '3   chromedriver                        0x00000001005dbf9b chromedriver + 622491', '4   chromedriver                        0x00000001005d7046 chromedriver + 602182', '5   chromedriver                        0x00000001005d2e3c chromedriver + 585276', '6   chromedriver                        0x0000000100615c43 chromedriver + 859203', '7   chromedriver                        0x000000010061574f chromedriver + 857935', '8   chromedriver                        0x000000010060db33 chromedriver + 826163', '9   chromedriver                        0x00000001005de9fd chromedriver + 633341', '10  chromedriver                        0x00000001005e0051 chromedriver + 639057', '11  chromedriver                        0x000000010099930e chromedriver + 4543246', '12  chromedriver                        0x000000010099da88 chromedriver + 4561544', '13  chromedriver                        0x00000001009a56df chromedriver + 4593375', '14  chromedriver                        0x000000010099e8fa chromedriver + 4565242', '15  chromedriver                        0x00000001009742cf chromedriver + 4391631', '16  chromedriver                        0x00000001009bd5b8 chromedriver + 4691384', '17  chromedriver                        0x00000001009bd739 chromedriver + 4691769', '18  chromedriver                        0x00000001009d381e chromedriver + 4782110', '19  libsystem_pthread.dylib             0x00007ff81f61d4e1 _pthread_start + 125', '20  libsystem_pthread.dylib             0x00007ff81f618f6b thread_start + 15', '', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 71, in start', '    self.process = subprocess.Popen(cmd, env=self.env,', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__', '    self._execute_child(args, executable, preexec_fn, close_fds,', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child', '    raise child_exception_type(errno_num, err_msg, err_filename)', "FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'", '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/AutoLoginZerodha.py", line 117, in auto_login_zerodha', '    key = automate_login(browser_url, user_id, password, totp_pin)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/AutoLoginZerodha.py", line 40, in automate_login', '    browser = webdriver.Chrome(options = options)', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__', '    super(WebDriver, self).__init__(DesiredCapabilities.CHROME[\'browserName\'], "goog",', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__', '    self.service.start()', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 81, in start', '    raise WebDriverException(', "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home", '']
root - CRITICAL - CRITICAL ERROR:2023-02-20 09:47:43.010518 - Failed to initialise Log server/ADS.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 36, in __init__', '    self.start()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 44, in start', '    self.main_loop()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 84, in main_loop', '    sleep(1)', 'KeyboardInterrupt']
root - INFO - 2023-02-20 10:14:03.506970 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-02-20 10:14:03.614173 - OMS Backend mainloop started.
root - INFO - 2023-02-20 10:14:05.721500 - OMSB: Logging in for backend kite ticker.
root - CRITICAL - CRITICAL ERROR:2023-02-20 10:14:08.872134 - OMSB: Failed auto login to kite ticker.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/AutoLoginKiteTicker.py", line 36, in automate_login', "    browser = webdriver.Chrome(options = options,executable_path='../Chrome/chromedriver')", '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__', '    super(WebDriver, self).__init__(DesiredCapabilities.CHROME[\'browserName\'], "goog",', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__', '    self.service.start()', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 98, in start', '    self.assert_process_still_running()', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running', '    raise WebDriverException(', 'selenium.common.exceptions.WebDriverException: Message: Service ../Chrome/chromedriver unexpectedly exited. Status code was: -9', '', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 71, in start', '    self.process = subprocess.Popen(cmd, env=self.env,', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__', '    self._execute_child(args, executable, preexec_fn, close_fds,', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child', '    raise child_exception_type(errno_num, err_msg, err_filename)', "FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'", '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/AutoLoginKiteTicker.py", line 124, in auto_login_zerodha_ticker', '    key = automate_login(browser_url, user_id, password, totp_pin, debug=debug)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/AutoLoginKiteTicker.py", line 40, in automate_login', '    browser = webdriver.Chrome(options = options)', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__', '    super(WebDriver, self).__init__(DesiredCapabilities.CHROME[\'browserName\'], "goog",', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__', '    self.service.start()', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 81, in start', '    raise WebDriverException(', "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home", '']
root - CRITICAL - CRITICAL ERROR:2023-02-20 10:14:08.998297 - Failed to initialise LTP gather module.
['Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn', '    conn = connection.create_connection(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection', '    raise err', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection', '    sock.connect(sa)', 'ConnectionRefusedError: [Errno 61] Connection refused', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen', '    httplib_response = self._make_request(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request', '    conn.request(method, url, **httplib_request_kw)', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request', '    super(HTTPConnection, self).request(method, url, body=body, headers=headers)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request', '    self._send_request(method, url, body, headers, encode_chunked)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1331, in _send_request', '    self.endheaders(body, encode_chunked=encode_chunked)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1280, in endheaders', '    self._send_output(message_body, encode_chunked=encode_chunked)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1040, in _send_output', '    self.send(msg)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 980, in send', '    self.connect()', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect', '    conn = self._new_conn()', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn', '    raise NewConnectionError(', 'urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1494510a0>: Failed to establish a new connection: [Errno 61] Connection refused', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 440, in send', '    resp = conn.urlopen(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen', '    retries = retries.increment(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment', '    raise MaxRetryError(_pool, url, error or ResponseError(cause))', "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1494510a0>: Failed to establish a new connection: [Errno 61] Connection refused'))", '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/GatherLTP.py", line 30, in __init__', '    self.OMS_interface = OMS_API_Interface.OMS_Interface(Config().OMS_SERVER_ADDRESS)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/OMS_API_Interface.py", line 12, in __init__', '    self.token = self.authentification()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/OMS_API_Interface.py", line 23, in authentification', "    response = requests.post(self.url + 'token', data=data)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 117, in post', "    return request('post', url, data=data, json=json, **kwargs)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 61, in request', '    return session.request(method=method, url=url, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 529, in request', '    resp = self.send(prep, **send_kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 645, in send', '    r = adapter.send(request, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 519, in send', '    raise ConnectionError(e, request=request)', "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1494510a0>: Failed to establish a new connection: [Errno 61] Connection refused'))"]
root - CRITICAL - CRITICAL ERROR:2023-02-20 10:14:09.103415 - Failed to start KWS thread.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/GatherLTP.py", line 71, in start', '    self.kws.on_ticks = self.on_ticks', "AttributeError: 'NoneType' object has no attribute 'on_ticks'"]
root - INFO - 2023-02-20 10:14:09.103918 - Attempting XTS login.
root - INFO - 2023-02-20 10:14:09.354913 - OMSB: Zerodha login for WG5235.
root - CRITICAL - CRITICAL ERROR:2023-02-20 10:14:09.439876 - Failed to generate user dictionary.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 72, in main_loop', '    user_dict = UserProfileGenerator().create_user_profiles(user_data=user_data, log_interface=self.log_interface, debug=self.DEBUG)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/UserProfileGenerator.py", line 68, in create_user_profiles', '    t.join()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1053, in join', '    self._wait_for_tstate_lock()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1073, in _wait_for_tstate_lock', '    if lock.acquire(block, timeout):', 'KeyboardInterrupt']
root - CRITICAL - CRITICAL ERROR:2023-02-20 10:14:09.543606 - Failure in order handler.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 78, in main_loop', '    order_handler = OrderHandler(user_profiles=user_dict, spread_list=spread_list, log_interface = self.log_interface, debug=self.DEBUG)', "UnboundLocalError: local variable 'user_dict' referenced before assignment"]
root - CRITICAL - CRITICAL ERROR:2023-02-20 10:14:12.494747 - OMSB: Failed auto login to kite for user:WG5235.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/AutoLoginZerodha.py", line 36, in automate_login', "    browser = webdriver.Chrome(options = options,executable_path='../Chrome/chromedriver')", '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__', '    super(WebDriver, self).__init__(DesiredCapabilities.CHROME[\'browserName\'], "goog",', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__', '    self.service.start()', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 98, in start', '    self.assert_process_still_running()', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running', '    raise WebDriverException(', 'selenium.common.exceptions.WebDriverException: Message: Service ../Chrome/chromedriver unexpectedly exited. Status code was: -9', '', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 71, in start', '    self.process = subprocess.Popen(cmd, env=self.env,', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__', '    self._execute_child(args, executable, preexec_fn, close_fds,', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child', '    raise child_exception_type(errno_num, err_msg, err_filename)', "FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'", '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/AutoLoginZerodha.py", line 117, in auto_login_zerodha', '    key = automate_login(browser_url, user_id, password, totp_pin)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/AutoLoginZerodha.py", line 40, in automate_login', '    browser = webdriver.Chrome(options = options)', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__', '    super(WebDriver, self).__init__(DesiredCapabilities.CHROME[\'browserName\'], "goog",', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__', '    self.service.start()', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 81, in start', '    raise WebDriverException(', "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home", '']
root - CRITICAL - CRITICAL ERROR:2023-02-20 10:14:12.848704 - Failed to initialise Log server/ADS.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 36, in __init__', '    self.start()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 44, in start', '    self.main_loop()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 84, in main_loop', '    sleep(1)', 'KeyboardInterrupt']
root - INFO - 2023-02-20 10:14:58.989700 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-02-20 10:14:59.103369 - OMS Backend mainloop started.
root - INFO - 2023-02-20 10:15:01.115523 - OMSB: Logging in for backend kite ticker.
root - CRITICAL - CRITICAL ERROR:2023-02-20 10:15:25.405905 - OMSB: Failed auto login to kite ticker.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/AutoLoginKiteTicker.py", line 36, in automate_login', "    browser = webdriver.Chrome(options = options,executable_path='../Chrome/chromedriver')", '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__', '    super(WebDriver, self).__init__(DesiredCapabilities.CHROME[\'browserName\'], "goog",', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__', '    self.service.start()', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 103, in start', '    sleep(0.5)', 'KeyboardInterrupt', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 71, in start', '    self.process = subprocess.Popen(cmd, env=self.env,', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__', '    self._execute_child(args, executable, preexec_fn, close_fds,', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child', '    raise child_exception_type(errno_num, err_msg, err_filename)', "FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'", '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/AutoLoginKiteTicker.py", line 124, in auto_login_zerodha_ticker', '    key = automate_login(browser_url, user_id, password, totp_pin, debug=debug)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/AutoLoginKiteTicker.py", line 40, in automate_login', '    browser = webdriver.Chrome(options = options)', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__', '    super(WebDriver, self).__init__(DesiredCapabilities.CHROME[\'browserName\'], "goog",', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__', '    self.service.start()', '  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 81, in start', '    raise WebDriverException(', "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home", '']
root - CRITICAL - CRITICAL ERROR:2023-02-20 10:15:25.529509 - Failed to initialise LTP gather module.
['Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn', '    conn = connection.create_connection(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection', '    raise err', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection', '    sock.connect(sa)', 'ConnectionRefusedError: [Errno 61] Connection refused', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen', '    httplib_response = self._make_request(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request', '    conn.request(method, url, **httplib_request_kw)', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request', '    super(HTTPConnection, self).request(method, url, body=body, headers=headers)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request', '    self._send_request(method, url, body, headers, encode_chunked)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1331, in _send_request', '    self.endheaders(body, encode_chunked=encode_chunked)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1280, in endheaders', '    self._send_output(message_body, encode_chunked=encode_chunked)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1040, in _send_output', '    self.send(msg)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 980, in send', '    self.connect()', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect', '    conn = self._new_conn()', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn', '    raise NewConnectionError(', 'urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x149778640>: Failed to establish a new connection: [Errno 61] Connection refused', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 440, in send', '    resp = conn.urlopen(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen', '    retries = retries.increment(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment', '    raise MaxRetryError(_pool, url, error or ResponseError(cause))', "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x149778640>: Failed to establish a new connection: [Errno 61] Connection refused'))", '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/GatherLTP.py", line 30, in __init__', '    self.OMS_interface = OMS_API_Interface.OMS_Interface(Config().OMS_SERVER_ADDRESS)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/OMS_API_Interface.py", line 12, in __init__', '    self.token = self.authentification()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/OMS_API_Interface.py", line 23, in authentification', "    response = requests.post(self.url + 'token', data=data)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 117, in post', "    return request('post', url, data=data, json=json, **kwargs)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 61, in request', '    return session.request(method=method, url=url, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 529, in request', '    resp = self.send(prep, **send_kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 645, in send', '    r = adapter.send(request, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 519, in send', '    raise ConnectionError(e, request=request)', "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x149778640>: Failed to establish a new connection: [Errno 61] Connection refused'))"]
root - CRITICAL - CRITICAL ERROR:2023-02-20 10:15:25.567901 - Failed to start LTP thread.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 65, in main_loop', '    g = GatherLTP(kws = kite_ticker, log_interface = self.log_interface)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/GatherLTP.py", line 47, in __init__', '    self.log_interface.postLog(severity="CRITICAL",message=\'Failed to initialise LTP gather module.\',publish = 1, tag = \'OMSB_GLTP_1\')', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Log_Server_Interface.py", line 55, in postLog', "    response = requests.post(self.url + 'post/log', headers=headers, json=json_compatible_item_data)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 117, in post', "    return request('post', url, data=data, json=json, **kwargs)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 61, in request', '    return session.request(method=method, url=url, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 529, in request', '    resp = self.send(prep, **send_kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 645, in send', '    r = adapter.send(request, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 440, in send', '    resp = conn.urlopen(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen', '    httplib_response = self._make_request(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request', '    six.raise_from(e, None)', '  File "<string>", line 3, in raise_from', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request', '    httplib_response = conn.getresponse()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1377, in getresponse', '    response.begin()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 320, in begin', '    version, status, reason = self._read_status()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 281, in _read_status', '    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto', '    return self._sock.recv_into(b)', 'KeyboardInterrupt']
root - INFO - 2023-02-20 10:15:25.697708 - Attempting XTS login.
root - CRITICAL - CRITICAL ERROR:2023-02-20 10:15:25.725700 - Failed to generate user dictionary.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 72, in main_loop', '    user_dict = UserProfileGenerator().create_user_profiles(user_data=user_data, log_interface=self.log_interface, debug=self.DEBUG)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/UserProfileGenerator.py", line 68, in create_user_profiles', '    t.join()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1053, in join', '    self._wait_for_tstate_lock()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1073, in _wait_for_tstate_lock', '    if lock.acquire(block, timeout):', 'KeyboardInterrupt']
root - CRITICAL - CRITICAL ERROR:2023-02-20 10:15:25.868234 - Failure in order handler.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 78, in main_loop', '    order_handler = OrderHandler(user_profiles=user_dict, spread_list=spread_list, log_interface = self.log_interface, debug=self.DEBUG)', "UnboundLocalError: local variable 'user_dict' referenced before assignment"]
root - INFO - 2023-02-20 10:15:25.873473 - OMSB: Zerodha login for WG5235.
root - CRITICAL - CRITICAL ERROR:2023-02-20 10:15:25.895265 - Failed to initialise Log server/ADS.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 36, in __init__', '    self.start()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 44, in start', '    self.main_loop()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 81, in main_loop', '    self.log_interface.postLog(severity="CRITICAL",message=\'Failure in order handler.\',publish = 1, tag = \'OMSB_MAIN_5\')', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Log_Server_Interface.py", line 55, in postLog', "    response = requests.post(self.url + 'post/log', headers=headers, json=json_compatible_item_data)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 117, in post', "    return request('post', url, data=data, json=json, **kwargs)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 61, in request', '    return session.request(method=method, url=url, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 529, in request', '    resp = self.send(prep, **send_kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 645, in send', '    r = adapter.send(request, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 440, in send', '    resp = conn.urlopen(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen', '    httplib_response = self._make_request(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request', '    six.raise_from(e, None)', '  File "<string>", line 3, in raise_from', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request', '    httplib_response = conn.getresponse()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1377, in getresponse', '    response.begin()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 320, in begin', '    version, status, reason = self._read_status()', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 281, in _read_status', '    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto', '    return self._sock.recv_into(b)', 'KeyboardInterrupt']
root - INFO - 2023-02-20 10:15:41.685429 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-02-20 10:15:41.799732 - OMS Backend mainloop started.
root - INFO - 2023-02-20 10:15:43.898556 - OMSB: Logging in for backend kite ticker.
root - INFO - 2023-02-20 10:15:54.758907 - OMSB: Login succesful for backend kite ticker.
root - CRITICAL - CRITICAL ERROR:2023-02-20 10:15:54.876624 - Failed to initialise LTP gather module.
['Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn', '    conn = connection.create_connection(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection', '    raise err', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection', '    sock.connect(sa)', 'ConnectionRefusedError: [Errno 61] Connection refused', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen', '    httplib_response = self._make_request(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request', '    conn.request(method, url, **httplib_request_kw)', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request', '    super(HTTPConnection, self).request(method, url, body=body, headers=headers)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request', '    self._send_request(method, url, body, headers, encode_chunked)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1331, in _send_request', '    self.endheaders(body, encode_chunked=encode_chunked)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1280, in endheaders', '    self._send_output(message_body, encode_chunked=encode_chunked)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1040, in _send_output', '    self.send(msg)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 980, in send', '    self.connect()', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect', '    conn = self._new_conn()', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn', '    raise NewConnectionError(', 'urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x13776f1c0>: Failed to establish a new connection: [Errno 61] Connection refused', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 440, in send', '    resp = conn.urlopen(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen', '    retries = retries.increment(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment', '    raise MaxRetryError(_pool, url, error or ResponseError(cause))', "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x13776f1c0>: Failed to establish a new connection: [Errno 61] Connection refused'))", '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/GatherLTP.py", line 30, in __init__', '    self.OMS_interface = OMS_API_Interface.OMS_Interface(Config().OMS_SERVER_ADDRESS)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/OMS_API_Interface.py", line 12, in __init__', '    self.token = self.authentification()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/OMS_API_Interface.py", line 23, in authentification', "    response = requests.post(self.url + 'token', data=data)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 117, in post', "    return request('post', url, data=data, json=json, **kwargs)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 61, in request', '    return session.request(method=method, url=url, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 529, in request', '    resp = self.send(prep, **send_kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 645, in send', '    r = adapter.send(request, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 519, in send', '    raise ConnectionError(e, request=request)', "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x13776f1c0>: Failed to establish a new connection: [Errno 61] Connection refused'))"]
root - INFO - 2023-02-20 10:15:54.999511 - Attempting XTS login.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
root - INFO - 2023-02-20 10:15:55.173185 - OMSB: Zerodha login for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
root - INFO - 2023-02-20 10:16:02.850055 - OMSB: Zerodha login succesful for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
root - CRITICAL - CRITICAL ERROR:2023-02-20 10:16:04.458466 - Failed to initialise Log server/ADS.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 36, in __init__', '    self.start()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 44, in start', '    self.main_loop()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 84, in main_loop', '    sleep(1)', 'KeyboardInterrupt']
root - INFO - 2023-02-20 10:16:40.949380 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-02-20 10:16:41.060488 - OMS Backend mainloop started.
root - INFO - 2023-02-20 10:16:43.152964 - OMSB: Logging in for backend kite ticker.
root - INFO - 2023-02-20 10:16:51.411403 - OMSB: Login succesful for backend kite ticker.
root - INFO - 2023-02-20 10:16:51.820370 - Attempting XTS login.
root - INFO - 2023-02-20 10:16:52.002797 - OMSB: Zerodha login for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-02-20 10:16:59.707075 - OMSB: Zerodha login succesful for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - CRITICAL - CRITICAL ERROR:2023-02-20 10:18:53.158954 - Failed to initialise Log server/ADS.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 36, in __init__', '    self.start()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 44, in start', '    self.main_loop()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 84, in main_loop', '    sleep(1)', 'KeyboardInterrupt']
root - INFO - 2023-02-20 10:54:12.415433 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-02-20 10:54:12.519658 - OMS Backend mainloop started.
root - INFO - 2023-02-20 10:54:14.694577 - OMSB: Logging in for backend kite ticker.
root - INFO - 2023-02-20 10:54:25.350873 - OMSB: Login succesful for backend kite ticker.
root - CRITICAL - CRITICAL ERROR:2023-02-20 10:54:25.461445 - Failed to initialise LTP gather module.
['Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn', '    conn = connection.create_connection(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection', '    raise err', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection', '    sock.connect(sa)', 'ConnectionRefusedError: [Errno 61] Connection refused', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen', '    httplib_response = self._make_request(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request', '    conn.request(method, url, **httplib_request_kw)', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request', '    super(HTTPConnection, self).request(method, url, body=body, headers=headers)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request', '    self._send_request(method, url, body, headers, encode_chunked)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1331, in _send_request', '    self.endheaders(body, encode_chunked=encode_chunked)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1280, in endheaders', '    self._send_output(message_body, encode_chunked=encode_chunked)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1040, in _send_output', '    self.send(msg)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 980, in send', '    self.connect()', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect', '    conn = self._new_conn()', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn', '    raise NewConnectionError(', 'urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x136aafd60>: Failed to establish a new connection: [Errno 61] Connection refused', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 440, in send', '    resp = conn.urlopen(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen', '    retries = retries.increment(', '  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment', '    raise MaxRetryError(_pool, url, error or ResponseError(cause))', "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x136aafd60>: Failed to establish a new connection: [Errno 61] Connection refused'))", '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/GatherLTP.py", line 30, in __init__', '    self.OMS_interface = OMS_API_Interface.OMS_Interface(Config().OMS_SERVER_ADDRESS)', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/OMS_API_Interface.py", line 12, in __init__', '    self.token = self.authentification()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/OMS_API_Interface.py", line 23, in authentification', "    response = requests.post(self.url + 'token', data=data)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 117, in post', "    return request('post', url, data=data, json=json, **kwargs)", '  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 61, in request', '    return session.request(method=method, url=url, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 529, in request', '    resp = self.send(prep, **send_kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 645, in send', '    r = adapter.send(request, **kwargs)', '  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 519, in send', '    raise ConnectionError(e, request=request)', "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x136aafd60>: Failed to establish a new connection: [Errno 61] Connection refused'))"]
root - INFO - 2023-02-20 10:54:25.578500 - Attempting XTS login.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
root - INFO - 2023-02-20 10:54:25.798576 - OMSB: Zerodha login for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
root - INFO - 2023-02-20 10:54:34.939312 - OMSB: Zerodha login succesful for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Retrying connection. Retry attempt count: 7. Next retry in around: 49 seconds
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: 'GatherLTP' object has no attribute 'instrument_token_list')
root - CRITICAL - CRITICAL ERROR:2023-02-20 11:27:32.066548 - Failed to initialise Log server/ADS.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 36, in __init__', '    self.start()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 44, in start', '    self.main_loop()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 84, in main_loop', '    sleep(1)', 'KeyboardInterrupt']
root - INFO - 2023-02-20 11:27:36.196455 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-02-20 11:27:36.300612 - OMS Backend mainloop started.
root - INFO - 2023-02-20 11:27:38.279713 - OMSB: Logging in for backend kite ticker.
root - INFO - 2023-02-20 11:27:50.743782 - OMSB: Login succesful for backend kite ticker.
root - INFO - 2023-02-20 11:27:51.158555 - Attempting XTS login.
root - INFO - 2023-02-20 11:27:51.335003 - OMSB: Zerodha login for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-02-20 11:27:59.271474 - OMSB: Zerodha login succesful for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-02-20 11:33:48.636417 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-02-20 11:33:48.740688 - OMS Backend mainloop started.
root - INFO - 2023-02-20 11:33:50.701933 - OMSB: Logging in for backend kite ticker.
root - INFO - 2023-02-20 11:33:59.889434 - OMSB: Login succesful for backend kite ticker.
root - INFO - 2023-02-20 11:34:00.314510 - Attempting XTS login.
root - INFO - 2023-02-20 11:34:00.485653 - OMSB: Zerodha login for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-02-20 11:34:08.792032 - OMSB: Zerodha login succesful for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - CRITICAL - CRITICAL ERROR:2023-02-20 11:40:18.247467 - Failed to refresh lookup table.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/GatherLTP.py", line 64, in refresh_lookup_table', '    self.lookup_table = json.load(f)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 293, in load', '    return loads(fp.read(),', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads', '    return _default_decoder.decode(s)', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode', '    obj, end = self.raw_decode(s, idx=_w(s, 0).end())', '  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode', '    raise JSONDecodeError("Expecting value", s, err.value) from None', 'json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)']
root - INFO - 2023-02-20 11:40:18.526575 - Placed Zerodha Kite options order for:FINVANT_LIVE, instrument:BANKNIFTY23FEB41000PE, qty:25, transaction type:BUY, placed price:270.85, id:230220500844547.
root - INFO - 2023-02-20 11:40:18.713816 - 368.41702461242676
root - INFO - 2023-02-20 11:40:20.305948 - Placed Zerodha Kite options order for:FINVANT_LIVE, instrument:BANKNIFTY23FEB41000CE, qty:-25, transaction type:SELL, placed price:286, id:230220500844682.
root - INFO - 2023-02-20 11:40:20.446420 - 1341.231107711792
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-02-20 11:55:16.203196 - Placed XTS options order for:MASTER_TRUST, instrument:NIFTY23FEB17950CE, qty:-50, transaction type:SELL, placed price:84.0, id:674.
root - INFO - 2023-02-20 11:55:16.362664 - 166.2459373474121
root - INFO - 2023-02-20 11:55:16.432085 - Placed Zerodha Kite options order for:FINVANT_LIVE, instrument:NIFTY23FEB17950CE, qty:-50, transaction type:SELL, placed price:83.55, id:230220500890468.
root - INFO - 2023-02-20 11:55:16.554473 - 368.65711212158203
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - CRITICAL - CRITICAL ERROR:2023-02-20 12:47:45.833291 - Failed to initialise Log server/ADS.
['Traceback (most recent call last):', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 36, in __init__', '    self.start()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 44, in start', '    self.main_loop()', '  File "/Users/aditya/Documents/dev/CloudAccess/CloudDownloads/OMS/Backend/Scripts/Main.py", line 84, in main_loop', '    sleep(1)', 'KeyboardInterrupt']
